### ISSUE TITLE
MTRR_FIX_COUNT has an incorrect value 

### ISSUE THREAD

**Issue by tandasat** [wbenny/ia32-doc#2]
`MTRR_FIX_COUNT` is meant to define the number of fixed-range MTRR entries, but it defines the number of "fixed-range MTRR MSRs" which consists of 8 MTRR entries for each.

`MTRR_FIX_COUNT` is defined as follows:
```
  - name: MTRR_FIX_COUNT
    description: |
      Architecture defined number of fixed range MTRRs (1 for 64k, 2 for 16k, 8 for 4k).
    tag: Custom
    value: (1 + 2 + 8)
```
which results in this code:
```
#define IA32_MTRR_FIX_COUNT                                          (1 + 2 + 8)
```
But it should be ` (1 + 2 + 8) * 8` as per `11.11.2.2 Fixed Range MTRRs` in Intel SDM.

(reporting back the same issue as you found in my code :-) )

By the way, this is an awesome project.

**Comment by wbenny** [comment]
Am I having deja vu... :) Thanks for the report, I'll fix it.

**Comment by tandasat** [comment]
Thank you for fix!
