### ISSUE TITLE
MSR bitmaps have wrong size

### ISSUE THREAD

**Issue by namazso** [wbenny/ia32-doc#3]
https://github.com/wbenny/ia32-doc/blob/master/out/ia32.h#L17981

Here the msr bitmaps contain 128 bytes (1024 bits) while the manual states each of these are supposed to be 1024 **bytes** to account for 0x2000 msrs each

![image](https://user-images.githubusercontent.com/8676443/52850416-56ab9f00-310b-11e9-8ead-4f1b1add0018.png)

Also, thanks for this project

**Comment by wbenny** [comment]
Good catch, thanks a lot!
