### ISSUE TITLE
pde_2mb_64 is invalid

### ISSUE THREAD

**Issue by can1357** [wbenny/ia32-doc#4]
Hey!
pde_2mb_64 seems to be a duplicate of pdpte_1gb_64 as:

```
/**
* @brief Format of a 4-Level Page-Directory Entry that Maps a 2-MByte Page
*/
typedef union
{
	struct
	{
...
		/**
		* [Bits 47:30] Physical address of the 1-GByte page referenced by this entry.
		*/
		uint64_t page_frame_number : 18;
#define PDE_2MB_64_PAGE_FRAME_NUMBER_BIT                             30
#define PDE_2MB_64_PAGE_FRAME_NUMBER_FLAG                            0xFFFFC0000000
#define PDE_2MB_64_PAGE_FRAME_NUMBER_MASK                            0x3FFFF
#define PDE_2MB_64_PAGE_FRAME_NUMBER(_)                              (((_) >> 30) & 0x3FFFF)
		uint64_t reserved2 : 4;

...
	};

	uint64_t flags;
} pde_2mb_64;
```

Although the entry in intel-documentation declares:
> (M–1):21 Physical address of the 2-MByte page referenced by this entry

Not too sure what the problem is as I haven't gone over project source but wanted to let you know.

-----
P.S. I'd like to thank you for the time you spent on this great project, it's truely an invaluable resource.

**Comment by wbenny** [comment]
Good catch, thanks a lot!
